{
 "title": "Wireguard",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "peer_name",
    "label": "Peer name",
    "query": {
     "query": "label_values(wireguard_latest_handshake_timestamp{name=~\".+\"}, name)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Active peers",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(wireguard_peer_active) by (interface)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Peers activity over time",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 21, "x": 3, "y": 0 },
   "targets": [
    {
     "expr": "sum(wireguard_peer_active) by (name)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Throughput",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "-sum(rate(wireguard_bits_received{interface=\"wg0\", name=~\"${peer_name}\"}[5m])) by (interface)",
     "legendFormat": "Bits received $peer_name"
    },
    {
     "expr": "sum(rate(wireguard_bits_sent{interface=\"wg0\", name=~\"${peer_name}\"}[5m])) by (interface)",
     "legendFormat": "Bits sent $peer_name"
    }
   ]
  },
  {
   "title": "Bits received",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 13, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "sum(rate(wireguard_bits_received{interface=\"wg0\", name=~\"${peer_name}\"}[5m])) by (interface)",
     "legendFormat": "Bits received $peer_name"
    }
   ]
  },
  {
   "title": "Bits sent",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 11, "x": 13, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "sum(rate(wireguard_bits_sent{interface=\"wg0\", name=~\"${peer_name}\"}[5m])) by (interface)",
     "legendFormat": "Bits sent $peer_name"
    }
   ]
  }
 ]
}